### ISSUE TITLE
TypeError: Object #<Object> has no method 'debuglog'

### ISSUE THREAD

**Issue by barneycarroll** [caspervonb/amok#102]
Amok chokes on

```shell
/usr/lib/node_modules/amok/node_modules/rdbg/lib/index.js:7
const debug = util.debuglog('rdbg');
                   ^
TypeError: Object #<Object> has no method 'debuglog'
    at Object.<anonymous> (/usr/lib/node_modules/amok/node_modules/rdbg/lib/index.js:7:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/amok/lib/index.js:2:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by caspervonb** [comment]
Use a newer version of node, generally I've said use the 0.12 branch ([The getting started guide briefly mentions the required version](https://github.com/caspervonb/amok/blob/master/getting_started.md#installing-nodejs)) but 0.11 should work too if I am recalling node's changelog correctly.

Rationale for not supporting older node versions is basically two fold, amok was written recently, and doesn't have to run on specific cloud stacks etc, developer machines tend to have edge installed, or at-least nvm installed.

However, this is brought up frequently in the chat, so some action should probably be taken just not sure what to do about it. Add engine requirement to `package.json` perhaps?

**Comment by caspervonb** [comment]
Since the engines field is just advisory there's not much point in adding it, *i think*, I did not see any warning when installing with node v0.8.x.

I did add a note about it in the readme (https://github.com/caspervonb/amok/commit/3cc35762db514586fd7aa823f22e62e4fc169efc#diff-0730bb7c2e8f9ea2438b52e419dd86c9R20) and emphasis on it in the getting started guide (https://github.com/caspervonb/amok/commit/78e6c3df0c020dd700f676768b29dc25077ddfe5) however.

I'm not sure what else can be done here, the failure rate seems to be high, and I'm sure theres plenty of more installs that assume its broken and don't ask about it.

**Comment by caspervonb** [comment]
I changed the title of the issue to make it searchable, closing this.

**Comment by caspervonb** [comment]
Lastly, it's very explicitly pointed out in the video following the getting started guide added in https://github.com/caspervonb/amok/commit/abd2bcf81a0327d6eaa13499bab5e5d012711cde.

Hope this is all enough to keep this issue from being an issue, has been at-least 10 instances of it in the chat over the past couple of weeks. It's very likely that there are factors more people trying it and just assuming it's a broken piece of hunk than the ones that take the time to jump in the chat and ask.
